version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-container
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-container
    working_dir: /usr/src/app
    ports:
      - "5173:5173"

  postgres:
    image: postgres:13 # You can change the version if needed
    container_name: postgres-container
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"  # Exposes PostgreSQL port for external access
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists data between container restarts

volumes:
  postgres_data: 
