version: '3.8'

services:
  backend:
    build:
      context: ./server  # Path to the backend directory (adjust as needed)
      dockerfile: Dockerfile
    container_name: backend-container
    working_dir: /usr/src/app
    ports:
      - "3000:3000"  # Expose backend port
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]

  frontend:
    build:
      context: ./client  # Path to the frontend directory (adjust as needed)
      dockerfile: Dockerfile
    container_name: frontend-container
    working_dir: /usr/src/app
    ports:
      - "5174:5173"  # Expose frontend port (default Vite port)
    volumes:
      - ./client:/usr/src/app
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

networks:
  default:
    driver: bridge
