version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-container
    working_dir: /usr/src/app
    ports:
      - "3000:3000"  
    #   - ./server:/usr/src/app
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]

  frontend:
    build:
      context: ./client 
      dockerfile: Dockerfile
    container_name: frontend-container
    working_dir: /usr/src/app
    ports:
      - "5174:5173"  
    # volumes:
    #   - ./client:/usr/src/app
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

networks:
  default:
    driver: bridge
